var Locale = {
    transform: { ru: "Параметры обработки изображения", en: "Processing Settings", es: ""},
    mode: { ru: "Режим преобразования", en: "Conversion Mode", es: ""},
    mode_auto: { ru: "Авто-убрать шум и увеличить", en: "Magnify & Auto Denoise", es: ""},
    mode_noise_resize: { ru: "Убрать шум и увеличить", en: "Denoise & Magnify", es: ""},
    mode_resize: { ru: "Только увеличить", en: "Magnify only", es: ""},
    mode_noise: { ru: "Только шум", en: "", es: "Denoise only"},
    profiles: { ru: "Профиль", en: "Model", es: ""},
    profiles_1: { ru: "2D изображ. (Профиль UpRGB)", en: "2D Illust, (UpRGB Mode)", es: ""},
    profiles_2: { ru: "Фото (Профиль UpPhoto)", en: "Photo (UpPhoto Mode)", es: ""},
    profiles_3: { ru: "2D изображ. (Профиль RGB)", en: "2D Illust. (RGB Mode)", es: ""},
    profiles_4: { ru: "Фотография, Аниме", en: "Photography, Anime", es: ""},
    profiles_5: { ru: "2D изображ. (Профиль Y)", en: "2D Illust. (Y Mode)", es: ""},
    noise: { ru: "Уровень удаления шума", en: "Denoise Level", es: ""},
    block: { ru: "Размер блока", en: "Split Size", es: ""},
    ok: { ru: "Запуск", en: "Run", es: ""},
    cancel: { ru: "Отменить", en: "Cancel", es: ""},
    notfound: { ru: "не найден", en: "not found"},
    batushev: { ru: "Виталий Батушев", en: "Vitaly Batushev" }
}
